"""Semantic inventory of the always-on Android head surface.

Every entry is one contract that the STOCK surface (origin/main @ fbf8ce6)
stated, expressed as literal probes that must still be findable in the LEAN
surface. Leaning the head is only legitimate if this list stays at zero
missing -- the budget assertions in `test_lean_head_surface.py` are what make
the list load-bearing rather than decorative: without a budget, nothing pushes
on the text; without this list, the budget would be met by deleting contracts.

Two haystacks:

* ``tool``      -- the mounted android_inspector surface, i.e. its description
                   plus every parameter description (both are rendered into
                   every session that has the tool).
* ``awareness`` -- ``context/android-awareness.md``, injected as context.

A probe is a tuple of literals, ALL of which must be present. Probes are
deliberately literal (not fuzzy) so that a paraphrase which drops a named
value -- a pid, a range, a flag, an error mode -- fails loudly.
"""

from __future__ import annotations

TOOL_SEMANTICS: list[tuple[str, str, tuple[str, ...]]] = [
    # --- framing / sensor rule -------------------------------------------
    ("T-01", "drives and inspects Android apps on an adb-reachable device or emulator",
     ("Drive and inspect Android apps", "adb-reachable device or emulator")),
    ("T-02", "uiautomator is the sensor", ("uiautomator is the sensor",)),
    ("T-03", "every interaction resolves a selector against the live accessibility tree first",
     ("resolves a selector against the live accessibility tree before acting",)),
    ("T-04", "screenshots are for judgment, never for computing tap coordinates",
     ("visual judgment only, never for computing tap coordinates",)),
    # --- list_devices -----------------------------------------------------
    ("T-05", "list_devices enumerates attached devices", ("list_devices: enumerate attached devices",)),
    ("T-06", "list_devices errors on ambiguity", (">1 ready device, no explicit serial",)),
    ("T-07", "serial auto-resolves to the single ready device, else errors",
     ("uses the single ready device, or errors if zero/ambiguous",)),
    # --- start_emulator ---------------------------------------------------
    ("T-08", "start_emulator boots an AVD from avd/port", ("start_emulator: boot an AVD (avd, port)",)),
    ("T-09", "start_emulator applies host workarounds", ("host workarounds",)),
    ("T-10", "start_emulator returns the serial", ("returns serial",)),
    ("T-11", "a missing AVD fast-fails immediately, with no 60s timeout",
     ("fast-fails immediately (no 60s timeout)",)),
    ("T-12", "the fast-fail names the existing AVDs and the avdmanager remediation command",
     ("naming the AVDs", "avdmanager remediation command")),
    ("T-13", "'avd' is not 'name' (create_avd's new-AVD name)",
     ("Not 'name' (create_avd's new-AVD name)",)),
    ("T-14", "doctor/create_avd are how you provision an AVD", ("See 'doctor' and 'create_avd'",)),
    ("T-15", "start_emulator takes an exclusive cross-process lease on the AVD first",
     ("exclusive cross-process lease on the AVD first",)),
    ("T-16", "it refuses if another live process already has that AVD booted",
     ("another live process has it booted",)),
    ("T-17", "the refusal names the owning pid/port/duration", ("owning pid/port/duration",)),
    ("T-18", "each unrelated session should use its own AVD", ("its own AVD", "see create_avd")),
    # --- port contract ----------------------------------------------------
    ("T-19", "port must be even and inside the range adb scans", ("Must be even", "5554-5682")),
    ("T-20", "console uses 'port', adb uses 'port + 1'", ("'port + 1' for adb",)),
    ("T-21", "invalid ports are rejected before launch, never silently ignored or adjusted",
     ("rejected before launch, never silently ignored or adjusted",)),
    ("T-22", "an explicit port waits on the deterministic serial, not 'any new serial'",
     ("deterministic serial", "'emulator-<port>'", "'any new serial'")),
    ("T-23", "it refuses if that serial is already attached to another device/emulator",
     ("already attached to another device/emulator",)),
    ("T-24", "an omitted port is allocated atomically, lowest free even port in range",
     ("allocated atomically", "lowest free even port in range")),
    ("T-25", "allocation skips ports attached in adb devices or held on another live AVD lease",
     ("already attached in adb devices or recorded on another live AVD lease",)),
    ("T-26", "it falls back to 'any new serial' only when every port is taken",
     ("only if every port is taken",)),
    ("T-27", "the fallback is named in the result as port_allocation_fallback",
     ("port_allocation_fallback",)),
    # --- stop_emulator ----------------------------------------------------
    ("T-28", "stop_emulator kills the emulator and reaps its process",
     ("kill the emulator and reap its process",)),
    ("T-29", "it refuses unless the calling session owns a live AVD lease for that serial",
     ("Refuses unless a live AVD lease for that serial is owned by the calling session",)),
    ("T-30", "it names the owning pid rather than silently killing someone else's emulator",
     ("names the owning pid rather than silently killing someone else's emulator",)),
    ("T-31", "'force' stops a serial whose lease is held by a DIFFERENT live process",
     ("stop_emulator: stop a serial whose AVD lease is held by a DIFFERENT live process",)),
    ("T-32", "'force' also covers the no-lease-record-at-all case", ("no lease record at all",)),
    ("T-33", "a cross-owner kill always carries a warning naming whose emulator died",
     ("'warning' field naming whose emulator was killed", "never")),
    # --- doctor / create_avd ---------------------------------------------
    ("T-34", "doctor reports the full host readiness check list",
     ("ANDROID_HOME, adb, emulator binary, KVM, ptrace_scope/gdb, AVDs, cmdline-tools",)),
    ("T-35", "every doctor check runs even if an earlier one fails",
     ("every check runs even if an earlier one fails",)),
    ("T-36", "doctor never errors and always returns a report",
     ("never errors, always returns a report",)),
    ("T-37", "create_avd provisions from an installed or sdkmanager-installable system image",
     ("installed or sdkmanager-installable system image",)),
    ("T-38", "create_avd never clobbers an existing AVD",
     ("never clobbers an existing AVD", "silently clobbering")),
    ("T-39", "create_avd never silently accepts SDK licenses",
     ("silently accepts SDK licenses", "silently accepting licenses on your behalf")),
    ("T-40", "accept_licenses defaults to False and fails loud", ("False (default) fails loud",)),
    ("T-41", "create_avd takes a new AVD name", ("New AVD name to create (create_avd)",)),
    ("T-42", "create_avd api_level names the system image API level",
     ("Android API level for the system image (create_avd)",)),
    ("T-43", "create_avd tag selects the system image tag",
     ("'google_apis', 'google_apis_playstore'",)),
    ("T-44", "create_avd abi defaults to the host's native ABI, detected not hardcoded",
     ("arm64-v8a on aarch64", "detected, never hardcoded")),
    ("T-45", "create_avd device is an avdmanager device profile",
     ("avdmanager device profile, e.g. 'pixel_6'",)),
    # --- app lifecycle ----------------------------------------------------
    ("T-46", "install reinstalls and grants all runtime perms",
     ("adb install -r -g (reinstall, grant all runtime perms)",)),
    ("T-47", "install takes an apk path", ("Path to a .apk (install)",)),
    ("T-48", "launch by component uses am start -n directly and is the most deterministic path",
     ("'am start -n'", "most deterministic")),
    ("T-49", "launch by package resolves the launcher activity via cmd package resolve-activity",
     ("'cmd package resolve-activity'",)),
    ("T-50", "monkey -c LAUNCHER is only the last resort when resolution yields nothing",
     ("'monkey -c LAUNCHER' only if that yields nothing",)),
    ("T-51", "component is preferred over package when known",
     ("Preferred over 'package' when known",)),
    ("T-52", "launch confirms arrival by polling mCurrentFocus for the target package",
     ("polling mCurrentFocus for the target package",)),
    ("T-53", "launch never reports success on exit code alone",
     ("never reports success on exit code alone",)),
    ("T-54", "timeout_s also bounds the launch arrival-confirmation poll",
     ("launch arrival-confirmation poll",)),
    ("T-55", "stop_app force-stops", ("stop_app: am force-stop",)),
    # --- sensing ----------------------------------------------------------
    ("T-56", "screenshot writes a PNG to disk and returns image_path, never inline base64",
     ("writes a PNG to disk, returns image_path (never inline base64)",)),
    ("T-57", "screenshot also returns geometry and byte size", ("geometry, byte size",)),
    ("T-58", "ui_dump returns a parsed node list with every documented field",
     ("class, text, content_desc, resource_id, bounds, center, focused, clickable, enabled",)),
    ("T-59", "ui_dump is not raw XML", ("not raw XML",)),
    ("T-60", "all_nodes widens ui_dump beyond nodes with text/desc/res-id",
     ("include all nodes, not just those with text/desc/res-id",)),
    ("T-61", "find returns matching nodes with resolved centers",
     ("nodes matching a selector, with resolved centers",)),
    ("T-62", "find does not error on 0 or >1 matches", ("does not error on 0 or >1 matches",)),
    ("T-63", "logcat tails, filtered by tag and/or package",
     ("logcat: tail, filtered by tag", "running package")),
    ("T-64", "filter_spec is a logcat filter spec", ("logcat: filter spec, e.g. 'MyTag:D *:S'",)),
    ("T-65", "lines bounds the trailing logcat dump", ("number of trailing lines to dump",)),
    ("T-66", "logcat resolves a package to its running pid(s) via pidof, else ps -A",
     ("running pid(s) (pidof, else", "'ps -A'")),
    ("T-67", "logcat scopes output to those pids with --pid", ("scopes output via --pid",)),
    ("T-68", "package composes with filter_spec rather than overriding it",
     ("composing with 'filter_spec' rather than overriding it",)),
    ("T-69", "logcat errors by name -- never an empty result -- if the package is not running",
     ("errors by name", "never an empty result", "no running process")),
    # --- interacting ------------------------------------------------------
    ("T-70", "tap follows dump -> resolve -> tap centre -> re-dump -> report",
     ("dump -> resolve selector -> tap center -> re-dump -> report what changed",)),
    ("T-71", "type_text follows the verified field-write protocol",
     ("tap -> assert focus -> MOVE_END + N*DEL -> input text -> BACK -> re-dump -> assert readback",)),
    ("T-72", "text is what type_text types", ("Text to type (type_text)",)),
    ("T-73", "key takes a keyevent name or a numeric code", ("by name (e.g. 'BACK') or numeric code",)),
    ("T-74", "keycode is the key operation's parameter", ("(key op)",)),
    ("T-75", "swipe takes explicit coordinates because gestures have no selector analogue",
     ("gestures have no selector analogue",)),
    ("T-76", "swipe start/end coordinates are named parameters",
     ("Swipe start X", "Swipe start Y", "Swipe end X", "Swipe end Y")),
    ("T-77", "swipe duration is in milliseconds", ("Swipe duration in milliseconds",)),
    ("T-78", "tap_xy is raw, unresolved, and always warns",
     ("RAW coordinates, no selector resolution", "always returns a warning")),
    ("T-79", "tap_xy's raw coordinates are named parameters",
     ("Raw X coordinate (tap_xy)", "Raw Y coordinate (tap_xy)")),
    # --- synchronising ----------------------------------------------------
    ("T-80", "wait_for polls ui_dump until the selector appears/disappears, or times out",
     ("polls ui_dump until a selector appears/disappears, or timeout",)),
    ("T-81", "wait_for exists so there are no bare sleeps", ("no bare sleeps",)),
    ("T-82", "absent inverts wait_for to wait for disappearance",
     ("wait_for succeeds when the selector disappears, not appears",)),
    ("T-83", "poll_s is wait_for's poll interval", ("Poll interval in seconds (wait_for)",)),
    ("T-84", "dismiss_anr detects/dismisses the ANR dialog", ("dismiss_anr: detect/dismiss an ANR", "isn't responding")),
    ("T-85", "an ANR is never auto-dismissed silently by other operations",
     ("never auto-dismissed silently by other operations",)),
    # --- selector contract ------------------------------------------------
    ("T-86", "selector supports text, res_id, desc, class+index and text_contains",
     ('{"text": "Save"}', '{"res_id": "com.foo:id/save"}', '{"desc": "Home"}',
      '{"class": "EditText", "index": 0}', '{"text_contains": "poll"}')),
    ("T-87", "multiple selector keys AND together", ("Multiple keys AND together",)),
    ("T-88", "an ambiguous match is an error that lists the candidates",
     ("An ambiguous match (>1 node, no index) is an error listing candidates",)),
    ("T-89", "the selector parameter enumerates its keys",
     ("text, text_contains, res_id, desc, class",)),
    ("T-90", "operation is the dispatch parameter", ("Operation to perform",)),
]

AWARENESS_SEMANTICS: list[tuple[str, str, tuple[str, ...]]] = [
    ("A-01", "the bundle drives Android apps on emulators AND physical devices",
     ("emulators and physical devices",)),
    ("A-02", "it does so via the android_inspector tool", ("`android_inspector`",)),
    ("A-03", "interaction is accessibility-tree driven", ("accessibility-tree-driven interaction",)),
    ("A-04", "verification is screenshot-based", ("screenshot-based visual verification",)),
    ("A-05", "the one rule: uiautomator is the sensor, the screenshot is for judgment not targeting",
     ("uiautomator is the sensor", "for judgment, never for targeting")),
    ("A-06", "coordinates come from ui_dump", ("Coordinates come from `ui_dump`",)),
    ("A-07", "what a screenshot legitimately answers",
     ("does this look right / what state am I in / is anything clipped",)),
    ("A-08", "a screenshot never answers 'where do I tap'", ('"where do I tap"',)),
    ("A-09", "the measured VLM miss: 61px horizontally, 93px vertically, on this host",
     ("61px horizontally", "93px vertically", "on this host")),
    ("A-10", "the derived tap centre fell outside the button",
     ("derived tap center fell outside the button",)),
    ("A-11", "the miss is silent", ("The miss is silent",)),
    ("A-12", "a tap on nothing or on a neighbouring field raises no error",
     ("lands on nothing, or on a neighbouring field, raises no error",)),
    ("A-13", "a recorded run typed a server URL into the API-key field and reported success",
     ("typed a server URL into the API-key field and reported success",)),
    ("A-14", "android-operator drives and verifies end-to-end",
     ("android-tester:android-operator", "boot emulator, install APK, launch app",
      "verify behaviour end-to-end")),
    ("A-15", "android-visual-tester judges how a screen looks",
     ("android-tester:android-visual-tester", "clipping/blank/overlap detection",
      "before/after visual comparison")),
    ("A-16", "android-debugger root-causes anomalies",
     ("android-tester:android-debugger", "why a tap did nothing", "frame/logcat correlation")),
    ("A-17", "do not run adb/uiautomator/emulator from the root session -- delegate",
     ("Delegate", "do not run `adb`, `uiautomator` or `emulator` from the root session")),
    ("A-18", "the agents hold the safety raw adb does not enforce",
     ("procedural safety raw adb does not enforce",)),
    ("A-19", "serial scoping on every call", ("serial scoping on every call",)),
    ("A-20", "dump-before-tap", ("dump-before-tap",)),
    ("A-21", "focus assertion before typing", ("focus assertion before typing",)),
    ("A-22", "KEYCODE_BACK commits fields", ("`KEYCODE_BACK` to commit fields",)),
    ("A-23", "aarch64 host workarounds", ("aarch64 host workarounds",)),
    ("A-24", "hand-driven adb is how two source projects installed onto the wrong emulator "
             "and typed into the wrong field",
     ("the two source projects silently installed an APK onto the wrong emulator",
      "typed a URL into the wrong field")),
    ("A-25", "destructive operations branch on serial shape",
     ("reinstall, `pm clear`, reboot", "`emulator-*` vs `<ip>:<port>`")),
    ("A-26", "because a physical device is not recoverable by re-running the test",
     ("not recoverable by re-running the test",)),
    ("A-27", "scope: on-device and emulator Android UI only",
     ("on-device and emulator Android UI only",)),
    ("A-28", "web UI/browsers/SPAs route to browser-tester", ("browsers, SPAs", "`browser-tester`")),
    ("A-29", "TUI and CLI route to terminal-tester", ("TUI and CLI", "`terminal-tester`")),
    ("A-30", "the Amplifier ecosystem itself routes to amplifier-tester",
     ("bundles, agents, sessions", "`amplifier-tester`")),
    ("A-31", "prerequisite: Android SDK at ANDROID_HOME, default ~/android-sdk, with emulator and adb",
     ("`ANDROID_HOME`", "`~/android-sdk`", "`emulator`", "working `adb`")),
    ("A-32", "prerequisite: /dev/kvm readable and writable", ("`/dev/kvm` readable and writable",)),
    ("A-33", "on aarch64 Linux Google's platform-tools adb is x86_64-only",
     ("aarch64 Linux", "`platform-tools/adb` is x86_64-only")),
    ("A-34", "Google ships no linux-aarch64 emulator build",
     ("linux-aarch64 emulator build (Google ships none)",)),
    ("A-35", "setup problems are a supported path, not a dead end", ("not a dead end",)),
    ("A-36", "doctor reports every host problem at once, each with its fix",
     ("every host problem at once, each with its fix",)),
    ("A-37", "create_avd provisions an AVD", ("`create_avd` provisions an AVD",)),
    ("A-38", "the bundle does not install the SDK", ("does not install the SDK",)),
    ("A-39", "missing prerequisites: agents report the exact fix and stop, never improvise",
     ("report the exact fix and stop", "improvise")),
]


def missing(semantics: list[tuple[str, str, tuple[str, ...]]], haystack: str) -> list[str]:
    """Return ``"<id>: <literal>"`` for every probe literal absent from haystack."""
    absent: list[str] = []
    for ident, _semantic, probes in semantics:
        for probe in probes:
            if probe not in haystack:
                absent.append(f"{ident}: {probe!r}")
    return absent
